### ISSUE TITLE
Overflow error

### ISSUE THREAD

**Issue by freQuensy23-coder** [DavidBuchanan314/unsafe-python#5]
In [1]: import unsafe

In [2]: unsafe.getmem
Out[2]: <function unsafe.getmem()>

In [3]: unsafe.getmem()
Out[3]: ---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
File ~/Documents/venv/lib/python3.11/site-packages/IPython/core/formatters.py:711, in PlainTextFormatter.__call__(self, obj)
    704 stream = StringIO()
    705 printer = pretty.RepresentationPrinter(stream, self.verbose,
    706     self.max_width, self.newline,
    707     max_seq_length=self.max_seq_length,
    708     singleton_pprinters=self.singleton_printers,
    709     type_pprinters=self.type_printers,
    710     deferred_pprinters=self.deferred_printers)
--> 711 printer.pretty(obj)
    712 printer.flush()
    713 return stream.getvalue()

File ~/Documents/venv/lib/python3.11/site-packages/IPython/lib/pretty.py:411, in RepresentationPrinter.pretty(self, obj)
    408                         return meth(obj, self, cycle)
    409                 if cls is not object \
    410                         and callable(cls.__dict__.get('__repr__')):
--> 411                     return _repr_pprint(obj, self, cycle)
    413     return _default_pprint(obj, self, cycle)
    414 finally:

File ~/Documents/venv/lib/python3.11/site-packages/IPython/lib/pretty.py:779, in _repr_pprint(obj, p, cycle)
    777 """A pprint that just redirects to the normal repr function."""
    778 # Find newlines and replace them with p.break_()
--> 779 output = repr(obj)
    780 lines = output.splitlines()
    781 with p.group():

OverflowError: bytearray object is too large to make repr

Im using python 3 11 9

**Comment by DavidBuchanan314** [comment]
This is expected behaviour, the bytearray is indeed too large to make repr
